<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

/**
 * Builds public/css/guest-icons.css from the Font Awesome SVGs in resources/icons/fa/{solid,regular,brands}/.
 *
 * Guest pages (the invitation, the RSVP pages, previews) draw their icons from this one small stylesheet instead of the
 * Font Awesome CDN stylesheet, which is render-blocking and from a third-party host. Templates keep their existing
 * `<i class="fa-solid fa-music">` markup: each icon is a rule that paints the SVG through `mask-image`, in the text colour.
 *
 * Add an icon: drop its SVG into the right folder (same Font Awesome Free version, see resources/icons/fa/LICENSE.txt), run
 * this command, commit both. `--check` fails when the committed stylesheet is out of date (the test suite runs it).
 * plans/invitation-page-compatibility.md Phase 4.
 */
class BuildGuestIconsCommand extends Command
{
    protected $signature = 'icons:build-guest-css {--check : Only report whether public/css/guest-icons.css is up to date}';

    protected $description = 'Build the guest-page icon stylesheet from resources/icons/fa';

    private const STYLES = ['solid' => 'fa-solid', 'regular' => 'fa-regular', 'brands' => 'fa-brands'];

    public function handle(): int
    {
        $css = $this->build();
        $target = public_path('css/guest-icons.css');

        if ($this->option('check')) {
            $current = is_file($target) ? file_get_contents($target) : '';
            if ($current !== $css) {
                $this->error('public/css/guest-icons.css is out of date. Run: php artisan icons:build-guest-css');

                return self::FAILURE;
            }
            $this->info('guest-icons.css is up to date.');

            return self::SUCCESS;
        }

        file_put_contents($target, $css);
        $this->info('Wrote public/css/guest-icons.css ('.number_format(strlen($css)).' bytes, '.substr_count($css, '--fa-icon: url').' icons).');

        return self::SUCCESS;
    }

    public function build(): string
    {
        $rules = [];

        foreach (self::STYLES as $folder => $class) {
            $files = glob(resource_path("icons/fa/{$folder}/*.svg")) ?: [];
            sort($files);

            foreach ($files as $file) {
                $name = basename($file, '.svg');
                $svg = (string) file_get_contents($file);

                if (! preg_match('/viewBox="0 0 (\d+(?:\.\d+)?) (\d+(?:\.\d+)?)"/', $svg, $m)) {
                    $this->warn("Skipped {$folder}/{$name}.svg: no viewBox");

                    continue;
                }
                $width = round((float) $m[1] / (float) $m[2], 3);

                $uri = $this->dataUri($svg);
                $rules[] = ".{$class}.fa-{$name} {\n    width: {$width}em;\n    --fa-icon: url(\"{$uri}\");\n}\n";
            }
        }

        return $this->header().$this->base()."\n".implode("\n", $rules);
    }

    private function header(): string
    {
        return <<<'CSS'
/*
 * GENERATED by `php artisan icons:build-guest-css` from resources/icons/fa. Do not edit by hand.
 *
 * Icons: Font Awesome Free 6.5.2 by @fontawesome, https://fontawesome.com, licensed CC BY 4.0
 * (https://creativecommons.org/licenses/by/4.0/). Each icon below is an unmodified Font Awesome Free SVG, painted with
 * mask-image so it takes the surrounding text colour. Copyright 2024 Fonticons, Inc.
 *
 * Used by guest-facing pages instead of the Font Awesome CDN stylesheet (layouts/site.blade.php, $guestPage).
 */

CSS;
    }

    private function base(): string
    {
        return <<<'CSS'
.fa-solid,
.fa-regular,
.fa-brands {
    display: inline-block;
    width: 1em;
    height: 1em;
    vertical-align: -0.125em;
    line-height: 1;
    font-style: normal;
    background-color: currentColor;
    -webkit-mask-repeat: no-repeat;
    mask-repeat: no-repeat;
    -webkit-mask-position: center;
    mask-position: center;
    -webkit-mask-size: contain;
    mask-size: contain;
    -webkit-mask-image: var(--fa-icon);
    mask-image: var(--fa-icon);
}

CSS;
    }

    /** The SVG as a compact data URI: the licence comment is dropped (it is in this file's header) and only what a URL needs is escaped. */
    private function dataUri(string $svg): string
    {
        $svg = preg_replace('/<!--.*?-->/s', '', $svg) ?? $svg;
        $svg = trim(preg_replace('/\s+/', ' ', $svg) ?? $svg);
        $svg = str_replace(['%', '"', '#', '<', '>'], ['%25', "'", '%23', '%3C', '%3E'], $svg);

        return 'data:image/svg+xml,'.$svg;
    }
}
